[tool.poetry]
name = "abmbiopsy"
version = "0.1.0"
description = "TODO add description here"
authors = ["Isabelle Chen <isabellechen2023@u.northwestern.edu>", "Alexis N. Prybutok <aprybutok@u.northwestern.edu", "Jessica S. Yu <jesyu@uw.edu>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "1.17.0"
pandas = "0.25.1"
matplotlib = "^3.0.3"
statsmodels = "0.11.1"

[tool.poetry.dev-dependencies]
tox = "^3.24.0"
pytest = "^6.2.4"
pylint = "^2.4"
pytest-cov = "^2.12.1"
Sphinx = "^4.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
